version: "3.9"

services:
  quiz_db:
    image: postgres:15-alpine
    container_name: quiz_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - quiz_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  quiz_cache:
    image: redis:7-alpine
    container_name: quiz_cache
    restart: always
    ports:
      - "${CACHE_PORT}:6379"
    volumes:
      - quiz_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  quiz_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz_backend
    restart: always
    environment:
      SECRET: ${SECRET}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      POSTGRES_HOST: quiz_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      GORM_LOG_LEVEL: ${GORM_LOG_LEVEL}
      BACKEND_PORT: ":8080"
    depends_on:
      quiz_db:
        condition: service_healthy
      quiz_cache:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT}:8080"

  quiz_panel:
    build:
      context: ./panel
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${PANEL_VITE_API_URL}
        QUIZ_FRONTEND: ${QUIZ_FRONTEND}
    container_name: quiz_panel
    restart: always
    depends_on:
      - quiz_backend
    ports:
      - "${PANEL_PORT}:81"

  quiz_front:
    build:
      context: ./quiz
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: ${QUIZ_VITE_API_URL}
    container_name: quiz_front
    restart: always
    depends_on:
      - quiz_backend
    ports:
      - "${QUIZ_PORT}:80"

volumes:
  quiz_postgres_data:
  quiz_redis_data:
